version = 0.1

[default.deploy.parameters]
stack_name = "qotd"
resolve_s3 = true
s3_prefix = "qotd"
region = "us-east-1"
profile = "cws"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
